# -*- coding: utf-8 -*-
"""Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Bài 2B.01 Nhập dữ liệu từ bàn phím dùng hàm input()
#a. Nhập vào kiểu chuỗi
#Ví dụ: nhập một chuỗi từ bàn phím vào biến chuoi1 và in ra chuỗi vừa nhập,
#in ra kiểu của chuỗi vừa nhập.
chuoi = input("Nhập 1 chỗi: ")
print (chuoi)
print(type(chuoi))

#Bài 2B.01 Nhập dữ liệu từ bàn phím dùng hàm input()
#b. Nhập vào kiểu int, float
# Kết quả trả về là một chuỗi có kiểu đối tượng là ‘str’.
# Để lấy đầu vào là số nguyên, số thực, chúng ta phải ép kiểu các
# đầu vào đó thành số nguyên bằng cách sử dụng hàm int(), float() tích hợp
# sẵn trong Python.

so_nguyen = int(input("Số nguyên: "))
print(so_nguyen)
print(type(so_nguyen))

so_thuc = float(input("Sô thực: "))
print(so_thuc)
print(type(so_thuc))

#c. Nhập vào kiểu danh sách
#Do giá trị trả về của hàm input là kiểu chuỗi, nếu muốn trả về dạng sanh sách chúng ta cần parse chuỗi thành danh sách dùng hàm split().
#Bằng cách duyệt danh sách từ hàm split() trả về chúng ta có thể ép kiểu chuỗi sang số nguyên, số thực. Ví dụ sau đây sẽ cho phép ép kiểu
lst_chuoi = input("Nhập ds: ").split()
print(lst_chuoi)
print(type(lst_chuoi))

lst_so_nguyen = [int(x) for x in input("Số nguyên: ").split()]
print(lst_so_nguyen)
print(type(lst_so_nguyen))

lst_so_thuc = [float(x) for x in input("Số thực: ").split()]
print(lst_so_thuc)
print(type(lst_so_thuc))

#Bài 2B.02: Lấy dữ liệu từ cửa sổ dòng lệnh
#Trong python có module gọi là sys, đây là module có sẵn. Trong module này có hàm argv, Hàm này trả về một danh sách các đối số dòng lệnh được truyền cho tập lệnh Python. Tên của tập lệnh luôn là mục ở chỉ số 0 và phần còn lại của các đối số được lưu trữ tại các chỉ mục tiếp theo.
# Để lấy được đối số ta làm:
import sys
doi_so = sys.argv
dem = len(doi_so)
print(type(doi_so))
i=0
for x in doi_so:
  print (f"tham số[{i}] = {x}, type({type(x)}")
  i += 1
print (f"Tổng số tham số = {dem}")

#Bài 2B.03. Gọi hàm main trong Python
#Hàm main trong Python là điểm bắt đầu của bất kỳ chương trình nào. Khi chương trình được chạy, trình thông dịch python chạy mã tuần tự. Hàm main chỉ được thực thi khi nó được chạy dưới dạng chương trình Python. Nó sẽ không chạy chức năng chính nếu nó được nhập dưới dạng mô-đun.
# Ở đây, chúng ta có hai phần của print() - một phần được định nghĩa trong hàm main là “Hello World!” và cái còn lại là độc lập, đó là “Hello Python!”. Khi chạy hàm def main(), chỉ “Hello Python!” in ra chứ không phải là "Hello World!". Đó là bởi vì chúng ta đã không khai báo hàm gọi function if  name   == "  main  ".
# Điều quan trọng là sau khi xác định hàm main, hãy gọi mã bằng if  name  " == " main  và sau đó chạy mã, chỉ khi đó mới nhận được đầu ra “hello world!” trong giao diện console. Hãy xem xét đoạn mã trong main_p2.py
#Ví dụ 1:
def main():
  print("Đinh Trung Vĩnh")
print("Cần Thơ")

##Bài 2B.03. Gọi hàm main trong Python
#Ví dụ 2:
def main():
  print("Đinh Trung Vĩnh")
if __name__ == "__main__":
    main()
print("Cần Thơ")

#Bài 2B.04 Chương trình hiển thị
#Xây dựng chương trình hiển thị ra màn hình thông tin sau:
#**************************
#
#*  LẬP TRÌNH VỚI PYTHON  *
#*  MSSV: NHAP_MA_SO_SV   *
#
#**************************
mssv = input("Nhập MSSV: ")

print("**************************")
print("\n")
print("* LẬP TRÌNH VỚI PYTHON   *")
print(f"* MSSV: {mssv}           *")
print("\n")
print("**************************")

#Bài 2B.05 Chương trình hiển thị
#Xây dựng chương trình hiển thị ra màn hình thông tin sau:
#* * * * * * * * * * *
#*                   *
#*                   *
#* * * * * * * * * * *

chieu_dai = 20
chieu_rong = 4

print("* " * (chieu_dai//2))

for i in range(chieu_rong - 2):
  print("*" + " " * (chieu_dai - 3) + "*")
print("* " * (chieu_dai // 2))

#Bài 2B.06 Chương trình hiển thị
#Hãy in màn hình hình chữ nhật như dưới đây:
#* * * * * * * * * *
#* * * * * * * * * *
#* * * * * * * * * *
#* * * * * * * * * *
# Sử dụng vòng lặp for để in 4 dòng
for _ in range(4):
    print("* * * * * * * * * *")

#Bài 2B.07 Chương trình hiển thị
# Xây dựng chương trình hiển thị ra màn hình các thông tin sau đây:
#Mời bạn chọn chức năng:
#1. Đăng nhập hệ thống
#2. Đăng xuất hệ thống
#3. Thoát khỏi hệ thống

print("Mời bạn chọn chức năng:")
print("1. Đăng nhập hệ thống")
print("2. Đăng xuất hệ thống")
print("3. Thoát khỏi hệ thống")

#Bài 2B.08 Hiển thị thông tin người dùng
#Xây dựng chương trình hiển thị thông tin của một người gồm: Họ tên, tuổi, giới tính, số
#điện thoại, email, địa chỉ, nghề nghiệp, mỗi thông tin trên một dòng. Với các thông tin về
#người dùng là đã biết trước và được lưu trong các biến thích hợp.
hoten = "Đinh Trung Vĩnh"
tuoi = 21
gioitinh = "Nam"
sdt = "0868477767"
email = "vinh01032004@gmail.com"
diachi = "Cần Thơ"
nghenghiep = "Sinh viên"

print("--THÔNG TIN SINH VIÊN--")
print(f"Họ tên: {hoten}")
print(f"Tuổi: {tuoi}")
print(f"Giới tính: {gioitinh}")
print(f"Số điện thoại: {sdt}")
print(f"Email: {email}")
print(f"Địa chỉ: {diachi}")
print(f"Nghề nghiệp: {nghenghiep}")

#Bài 3B.01 Tính lãi suất tiền gửi
#Một khách hàng A, có số tiền là Y, đem gửi tiết kiệm với lãi suất mỗi năm là x %. Chu kỳ
#gửi là 06 tháng, khi tới hạn thì tài khoản tiết kiệm sẽ tất toán và gửi tất cả &lt;tiền lãi&gt;, &lt;tiền
#gốc&gt; tiếp tục vào ngân hàng với lãi suất như cũ. Biết rằng nếu người dùng rút trước hạn
#thì sẽ tính lãi suất không kỳ hạn là 1,2 % trên năm. Hãy viết chương trình cho biết người
#dùng nhận được bao nhiêu tiền sau 18 và 20 tháng với Y tiền, lãi suất x được nhập từ bàn
#phím và đối số dòng lệnh.

import sys

def main():
    LAI_SUAT_KHONG_KY_HAN_NAM = 0.012

    so_tien_goc = float(input("Nhập tiền gửi: "))
    lai_suat_hang_nam = float(input("Nhập lãi suất hàng năm (ví dụ: 0.072): "))

    print(f"\nLãi suất hàng năm là: {lai_suat_hang_nam} %")

    print("\nChu kỳ tiết kiệm thứ 01: 01 - 06")
    print(f"Tiền gốc: {so_tien_goc:.1f}")
    lai_6_thang_1 = so_tien_goc * (lai_suat_hang_nam / 12) * 6
    print(f"Tiền lãi 6 tháng đầu là: {lai_6_thang_1:.0f}")
    tien_goc_moi_1 = so_tien_goc + lai_6_thang_1
    print(f"Tiền gốc + lãi 6 tháng đầu là: {tien_goc_moi_1:.1f}")

    print("\nChu kỳ tiết kiệm thứ 02: 07 - 12")
    print(f"Tiền gốc: {tien_goc_moi_1:.0f}")
    lai_6_thang_2 = tien_goc_moi_1 * (lai_suat_hang_nam / 12) * 6
    print(f"Tiền lãi 6 tháng tiếp theo là: {lai_6_thang_2:.0f}")
    tien_goc_moi_2 = tien_goc_moi_1 + lai_6_thang_2
    print(f"Tiền gốc + lãi 6 tiếp theo là: {tien_goc_moi_2:.1f}")

    print("\nChu kỳ tiết kiệm thứ 03: 13 - 18")
    print(f"Tiền gốc: {tien_goc_moi_2:.1f}")
    lai_6_thang_3 = tien_goc_moi_2 * (lai_suat_hang_nam / 12) * 6
    print(f"Tiền lãi 6 tháng tiếp theo là: {lai_6_thang_3:.0f}")
    tien_goc_moi_3 = tien_goc_moi_2 + lai_6_thang_3
    print(f"Tiền gốc + lãi 6 tiếp theo là: {tien_goc_moi_3:.1f}")

    print("\nChu kỳ tiết kiệm thứ 04: 19 - 20")
    print(f"Lãi suất không kỳ hạn: {LAI_SUAT_KHONG_KY_HAN_NAM} trên năm")
    print(f"Tiền gốc: {tien_goc_moi_3:.1f}")

    ho_va_ten_nhap = input("\nNhập họ và tên: ")
    print(f"Họ tên: {ho_va_ten_nhap}")

    lai_2_thang_cuoi = tien_goc_moi_3 * (LAI_SUAT_KHONG_KY_HAN_NAM / 12) * 2
    print(f"Tiền lãi 2 tháng cuối: {lai_2_thang_cuoi:.0f}")

    tien_cuoi_cung = tien_goc_moi_3 + lai_2_thang_cuoi
    print(f"Tiền gốc + lãi 2 tiếp theo là: {tien_cuoi_cung:.1f}")

if __name__ == "__main__":
    main()

#Bài 3B.02 Chuẩn hóa chuỗi
#Viết chương trình cho người dùng nhập vào một chuỗi họ tên của một người từ bàn phím
#và đối số dòng lệnh. Sau đó, hãy chuẩn hóa chuỗi họ tên thỏa mãn các yêu cầu sau:
#Chuỗi họ tên không chứa khoảng trống ở bên trái và bên phải chuỗi
# Ký tự đầu của họ, tên đệm, và tên phải viết hoa
# Chuỗi họ tên không chứa khoảng trắng thừa ở phần giữa họ, đệm, tên
# Hiển thị họ tên đã chuẩn hóa ra màn hình
import sys

def main():
    if len(sys.argv) > 1:
        ho_ten = ' '.join(sys.argv[1:])
    else:
        ho_ten = input("Nhap ho ten: ")

    ho_ten = ho_ten.strip()

    danh_sach_tu = ho_ten.split()

    danh_sach_tu_chuan = []
    for tu in danh_sach_tu:
        tu_chuan = tu.capitalize()
        danh_sach_tu_chuan.append(tu_chuan)

    ho_ten_chuan = ' '.join(danh_sach_tu_chuan)

    print("Ho ten da chuan hoa:", ho_ten_chuan)

if __name__ == "__main__":
    main()