# -*- coding: utf-8 -*-
"""Bản sao của Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nl9YNVyLR8Q_z_2FrupMhswPhj3Vm-lO
"""

#Bài 7B.01 Tính tổng hai đa thức
def nhap_da_thuc():
    bac = int(input("Nhập bậc của đa thức: "))
    he_so = []
    for i in range(bac, -1, -1):
        h = int(input(f"Nhập hệ số của x^{i}: "))
        he_so.append(h)
    return he_so

def cong_da_thuc(dt1, dt2):
    max_len = max(len(dt1), len(dt2))
    dt1 = [0]*(max_len-len(dt1)) + dt1
    dt2 = [0]*(max_len-len(dt2)) + dt2
    return [a+b for a,b in zip(dt1,dt2)]

def hien_thi(dt):
    s = ""
    bac = len(dt)-1
    for i, h in enumerate(dt):
        if h != 0:
            s += f"{h}x^{bac-i} + "
    return s[:-3]

# --- Main ---
print("Nhập đa thức 1:")
dt1 = nhap_da_thuc()
print("Nhập đa thức 2:")
dt2 = nhap_da_thuc()

tong = cong_da_thuc(dt1, dt2)
print("Tổng hai đa thức là:", hien_thi(tong))

#Bài 7B.02: Quản lý học sinh
#Viết chương trình quản lý học sinh thực hiện các chức năng sau:
#•	Nhập danh sách học sinh gồm các thông tin: Mã học sinh, tên học sinh, điểm toán, điểm tiếng Việt
#•	Hiển thị danh sách học sinh vừa nhập theo định dạng:
#Mã học sinh | Tên học sinh | Điểm Toán |	Điểm Tiếng Việt | Điểm Trung bình | Xếp loại
#Biết rằng Điểm trung bình = (Điểm Toán + Điểm Tiếng Việt) / 2 Xếp loại học sinh như sau:
#•	Nếu Điểm Trung bình lớn hơn hoặc bằng 9 thì xếp loại Xuất sắc
#•	Nếu Điểm Trung bình lớn hơn hoặc bằng 8 và nhỏ hơn 9 thì xếp loại Giỏi
#•	Nếu Điểm Trung bình lớn hơn hoặc bằng 7 và nhỏ hơn 8 thì xếp loại Khá
#•	Nếu Điểm Trung bình lớn hơn hoặc bằng 5 và nhỏ hơn 7 thì xếp loại Trung bình
#•	Nếu Điểm Trung bình nhỏ hơn 5 thì xếp loại Yếu

def xep_loai(diem_trungbinh):
  if diem_trungbinh >= 9:
    return "Xuat sac"
  elif diem_trungbinh >= 8:
    return "Gioi"
  elif diem_trungbinh >= 7:
    return "Kha"
  elif diem_trungbinh >= 5:
    return "Trung binh"
  else:
    return "Yeu"

#--- Main ---
danh_sach = []
so_luong_hs = int(input("Nhap so luong hoc sinh: "))
for i in range(so_luong_hs):
  print(f"\nHoc sinh {i+1}: ")
  ma_hs = input("Nhap ma hoc sinh: ")
  ten_hs = input("Nhap ten hoc sinh: ")
  toan = float(input("Nhap diem toan: "))
  tieng_viet = float(input("Nhap diem tieng viet: "))
  diem_trungbinh = (toan + tieng_viet) / 2
  xeploai = xep_loai(diem_trungbinh)
  danh_sach.append({
      "ma_hs":ma_hs,
      "ten_hs":ten_hs,
      "toan":toan,
      "tieng_viet":tieng_viet,
      "diem_trungbinh":diem_trungbinh,
      "xeploai":xeploai
  })

print("\nDanh sach hoc sinh:")
print(f"{'Ma HS':<10} | {'Ten HS':<15} | {'Toan':>6} | {'Tieng Viet':>11} | {'Trung binh':>12} | {'Xep loai':<12}")
print("-"*80)

for hs in danh_sach:
    print(f"{hs['ma_hs']:<10} | {hs['ten_hs']:<15} | {hs['toan']:>6.2f} | {hs['tieng_viet']:>11.2f} | {hs['diem_trungbinh']:>12.2f} | {hs['xeploai']:<12}")

#Bài 7B.03 Điểm trung bình
#Hãy sử dụng hàm trong Python để viết chương trình tính điểm trung bình của học sinh và in kết qua ra màn hình console. Bắt buộc phải sử dụng hàm để giải bài này.
#Chi tiết chương trình như sau:
#•	Nhập vào điểm các môn Toán, Lý, Hóa, Văn, Anh
#•	Tính điểm trung bình dựa vào 5 môn đó.
#Nếu:
#•	Điểm trung bình bé hơn 5 thì học lực yếu
#•	Điểm trung bình từ 5 - 6.9 thì học lực trung bình
#•	Điểm trung bình từ 7 - 8.9 là học lực khá
#•	Điểm trung bình từ 9 - 10 là học lực giỏi
def tinh_trungbinhmon(toan, ly, hoa, van, anh):
  return (toan + ly + hoa + van + anh) / 5

def xep_loai(diem_trungbinh):
  if diem_trungbinh < 5:
    return "Yeu"
  elif diem_trungbinh < 7:
    return "Trung binh"
  elif diem_trungbinh < 9:
    return "Kha"
  else:
    return "Gioi"

#---Main----
toan = float(input("Nhap diem toan: "))
ly = float(input("Nhap diem ly: "))
hoa = float(input("Nhap diem hoa: "))
van = float(input("Nhap diem van: "))
anh = float(input("Nhap diem anh: "))

diem_trungbinh = tinh_trungbinhmon(toan, ly, hoa, van, anh)
print(f"Diem trung binh: {diem_trungbinh}")
print(f"Hoc luc: ", xep_loai(diem_trungbinh))

#Bài 7B.04 Tổng số nguyên tố
#Hãy sử dụng hàm trong Python để viết chương trình tính tổng các số nguyên tố trong phạm vi từ 0 đến 1000
def la_nguyen_to(n):
    if n < 2: return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0: return False
    return True

tong = sum(i for i in range(1001) if la_nguyen_to(i))
print("Tổng số nguyên tố:", tong)

#Bài 7B.05 Giá trị lớn nhất
#Hãy viết một hàm Python dùng để tìm giá trị lớn nhất của ba số được nhập vào từ bàn phím,
#bạn có thể sử dụng hàm put để nhận dữ liệu từ người dùng.
def so_lon_nhat(a, b, c):
  return max(a, b, c)

a = float(input("Nhap so a: "))
b = float(input("Nhap so b: "))
c = float(input("Nhap so c: "))
print("So lon nhat la: ", so_lon_nhat(a, b, c))

#Bài 7B.06 Tính tổng
#Viết hàm dùng đệ quy và không dùng đệ quy để tính tổng S = 1 + 2 + 3 + 4 + 5 ... + n
def tong_dequy(n):
  if n == 1:
    return 1
  return  n + tong_dequy(n-1)

def khong_dequy(n):
  return sum(range(i, n+1))

n = int(input("Nhap n: "))
print("Tong bang de quy: ", tong_dequy(n))
print("Tong khong bang de quy: ", khong_dequy(n))

#Bài 7B.07 Đảo ngược chuỗi
#Viết hàm Python để đảo ngược một chuỗi
def dao_chuoi(s):
  return s[::-1]

chuoi = input("Nhap chuoi: ")
print("Chuoi dao nguoc la: ", dao_chuoi(chuoi))

#Bài 7B.08 Số giai thừa
#Viết hàm Python để tính giai thừa của một số (số nguyên không âm).
#Hàm chấp nhận một đối số đầu vào
def giaithua(n):
  if n == 0 or n == 1:
    return 1
  return n * giaithua(n-1)

n = int(input("Nhan so nguyen ko am: "))
print(f"{n} =", giaithua(n))

#Bài 7B.09 Tính số lượng chữ hoa và chữ thường của một chuỗi
#Viết hàm Python chấp nhận một chuỗi và tính số lượng chữ hoa và chữ thường
#•	Chuỗi mẫu: 'The quick Brow Fox'
#•	Đầu ra dự kiến:
  #o	Số ký tự chữ hoa : 3
  #o	Số ký tự chữ thường : 12
def dem_so_chu(chuoi):
  hoa = sum(1 for c in chuoi if c.isupper())
  thuong = sum(1 for c in chuoi if c.islower())
  return hoa, thuong

chuoi = "The quick Brow Fox"
hoa, thuong = dem_so_chu(chuoi)
print("So chu thuong: ", thuong)
print("So chu hoa: ", hoa)

#Bài 7B.10 Số nguyên tố
#Viết hàm Python nhận một số làm tham số và kiểm tra số đó có phải là số nguyên tố hay không?
def so_ngto(n):
  if n < 2:
    return False
  for i in range(2, int(n**0.5)+1):
    if n % i == 0:
      return False
  return True

n = int(input("Nhap so: "))
if so_ngto(n):
    print(f"{n} co phai la so nguyen to?", "\nKet qua: La so ngto")
else:
    print(f"{n} co phai la so nguyen to?", "\nKet qua: Ko phai so ngto")

#Bài 7B.11 Số hoàn hảo
#Viết hàm Python để kiểm tra xem một số có hoàn hảo hay không.
#Theo Wikipedia: Trong lý thuyết số, một số hoàn hảo là một số nguyên dương bằng tổng các ước số dương thực sự của nó, nghĩa là tổng các ước số dương của nó không bao gồm chính số đó (còn được gọi là tổng các phần tử của nó). Tương tự, một số hoàn hảo là một số bằng một nửa tổng của tất cả các ước dương của nó (bao gồm cả chính nó).
#Ví dụ : Số hoàn hảo đầu tiên là 6, vì 1, 2 và 3 là các ước dương thực sự của nó và 1 + 2 + 3 = 6. Tương tự, số 6 bằng một nửa tổng tất cả các ước dương của nó: ( 1 + 2 + 3 + 6 ) / 2
#= 6. Số hoàn hảo tiếp theo là 28 = 1 + 2 + 4 + 7 + 14. Tiếp theo là các số hoàn hảo 496 và 8128.
def so_hoanhao(n):
  tong = sum(i for i in range(1, n) if n % i == 0)
  return tong == n

n = int(input("Nhap so: "))
if so_hoanhao(n):
    print(f"{n} co phai la so hoan hao?", "\nKet qua: La so hoan hao")
else:
    print(f"{n} co phai la so hoan hao?", "\nKet qua: Ko phai so hoan hao")

#Bài 7B.12: Palindrome
#Viết một hàm Python để kiểm tra xem một chuỗi đã truyền có phải là palindrome hay không.
#Lưu ý: Palindrome là một từ, cụm từ hoặc trình tự đọc ngược cũng như đọc xuôi, ví dụ: madam.
def la_palindrome(s):
    return s == s[::-1]

s = input("Nhập chuỗi: ")
print("Palindrome?", la_palindrome(s))

#Bài 7B.13 Tam giác Pascal
#Viết hàm Python in ra n hàng đầu tiên của tam giác Pascal.
#Lưu ý: Tam giác Pascal là một hình số học và hình học do Blaise Pascal nghĩ ra đầu tiên.
def tam_giac_pascal(n):
    triangle = [[1]]
    for i in range(1, n):
        row = [1]
        for j in range(1, i):
            row.append(triangle[i-1][j-1] + triangle[i-1][j])
        row.append(1)
        triangle.append(row)
    return triangle

n = int(input("Nhập số hàng: "))
triangle = tam_giac_pascal(n)

for i in range(n):
    print(" " * (n - i), end="")
    for num in triangle[i]:
        print(num, end=" ")
    print()

#Bài 7B.14 Chuỗi Pangram
#Viết một hàm Python để kiểm tra xem một chuỗi có phải là một pangram hay không.
#Lưu ý: Pangram là những từ hoặc câu chứa mọi chữ cái trong bảng chữ cái ít nhất một lần. Ví dụ: "The quick brown fox jumps over the lazy dog"
def la_pangram(s):
    bang_chu_cai = "abcdefghijklmnopqrstuvwxyz"
    s = s.lower()
    for ch in bang_chu_cai:
        if ch not in s:
            return False
    return True

s = input("Nhập chuỗi: ")
print("Chuỗi có phải Pangram không?", "\n Kết quả:", la_pangram(s))

#Bài 7B.15 Chuyển đổi cơ số
#Viết hàm chuyển đổi các giữa các hệ nhị phân, thập phân, bát phân và thập lục phân. Với các tham số đầu vào là x, y, z được nhập từ bàn phím và đối số dòng lệnh. Với x là số cần chuyển đổi, y là hệ cơ số của x, z là cơ số cần chuyển đổi.
def chuyen_doi(x, y, z):
    so_thap_phan = int(str(x), y)
    if z == 2:
        return bin(so_thap_phan)[2:]
    elif z == 8:
        return oct(so_thap_phan)[2:]
    elif z == 16:
        return hex(so_thap_phan)[2:].upper()
    else:
        return str(so_thap_phan)

x = input("Nhập số cần chuyển đổi: ")
y = int(input("Nhập cơ số hiện tại của số (2, 8, 10, 16): "))
z = int(input("Nhập cơ số muốn chuyển sang (2, 8, 10, 16): "))

ket_qua = chuyen_doi(x, y, z)
print(f"Số {x} (cơ số {y}) = {ket_qua} (cơ số {z})")

#Bài 7B.16 Chuyển đổi hệ màu
#Viết hàm chuyển đổi giữa các mã màu Hex, RGB, CMYK, HSL
#•	hex_2_rgb(str)
#•	hex_2_cmyk(str)
#•	hex_2_hsl(str)
#•	rgb_2_hex(r, g, b)
#•	rgb_2_cmyk(r, g, b)
#•	rgb_2_hsl(r, g, b)
#•	hsl_2_rgb(h, s, l)
#•	hsl_2_hex(h, s, l)
#•	hsl_2_cmyk(h, s, l)
#•	cmyk_2_rgb(c, m, y, k)
#•	cmyk_2_hsl(c, m, y, k)
#•	cmyk_2_hex(c, m, y, k) Ví dụ:
#hex_2_rgb(“#1D9A55”) => 29, 154, 85
#hex_2_hsl(“#1D9A55”) => 146.88, 0.68, 0.36
#hex_2_cmyk(“#1D9A55”) => 49, 0, 27, 40
# Bài 7B.16: Chuyển đổi hệ màu
def hex_2_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) for i in (0,2,4))

def rgb_2_hex(r, g, b):
    return "#{:02X}{:02X}{:02X}".format(r, g, b)

def hex_2_cmyk(h):
    r, g, b = hex_2_rgb(h)
    if (r, g, b) == (0, 0, 0):
        return (0, 0, 0, 100)
    c = 1 - r/255
    m = 1 - g/255
    y = 1 - b/255
    k = min(c, m, y)
    c = (c - k) / (1 - k)
    m = (m - k) / (1 - k)
    y = (y - k) / (1 - k)
    return (round(c*100), round(m*100), round(y*100), round(k*100))

def rgb_2_cmyk(r, g, b):
    return hex_2_cmyk(rgb_2_hex(r, g, b))

def cmyk_2_rgb(c, m, y, k):
    c, m, y, k = c/100, m/100, y/100, k/100
    r = 255 * (1-c) * (1-k)
    g = 255 * (1-m) * (1-k)
    b = 255 * (1-y) * (1-k)
    return (round(r), round(g), round(b))

def cmyk_2_hex(c, m, y, k):
    r, g, b = cmyk_2_rgb(c, m, y, k)
    return rgb_2_hex(r, g, b)

# --- Main ---
while True:
    print("\nChọn chức năng:")
    print("1. HEX -> RGB")
    print("2. RGB -> HEX")
    print("3. HEX -> CMYK")
    print("4. RGB -> CMYK")
    print("5. CMYK -> RGB")
    print("6. CMYK -> HEX")
    print("0. Thoát")
    chon = input("Nhập lựa chọn: ")

    if chon == "0":
        break
    elif chon == "1":
        h = input("Nhập mã HEX (#RRGGBB): ")
        print("RGB =", hex_2_rgb(h))
    elif chon == "2":
        r = int(input("Nhập R (0-255): "))
        g = int(input("Nhập G (0-255): "))
        b = int(input("Nhập B (0-255): "))
        print("HEX =", rgb_2_hex(r, g, b))
    elif chon == "3":
        h = input("Nhập mã HEX (#RRGGBB): ")
        print("CMYK =", hex_2_cmyk(h))
    elif chon == "4":
        r = int(input("Nhập R (0-255): "))
        g = int(input("Nhập G (0-255): "))
        b = int(input("Nhập B (0-255): "))
        print("CMYK =", rgb_2_cmyk(r, g, b))
    elif chon == "5":
        c = int(input("Nhập C (0-100): "))
        m = int(input("Nhập M (0-100): "))
        y = int(input("Nhập Y (0-100): "))
        k = int(input("Nhập K (0-100): "))
        print("RGB =", cmyk_2_rgb(c, m, y, k))
    elif chon == "6":
        c = int(input("Nhập C (0-100): "))
        m = int(input("Nhập M (0-100): "))
        y = int(input("Nhập Y (0-100): "))
        k = int(input("Nhập K (0-100): "))
        print("HEX =", cmyk_2_hex(c, m, y, k))
    else:
        print("Lựa chọn không hợp lệ!")

#Bài 7B.17 BMI
#Viết hàm tính BMI (Body Mass Index) với dữ liệu đầu vào là cân nặng (kg) và chiều cao (cm). Sau đó, viết chương trình cho phép nhập cân nặng và chiều cao, giới tính, tuổi để đánh giá chỉ số BMI và gợi ý người dùng.
def tinh_bmi(can_nang, chieu_cao_cm):
    chieu_cao_m = chieu_cao_cm / 100
    return can_nang / (chieu_cao_m**2)

can_nang = float(input("Nhập cân nặng (kg): "))
cao = float(input("Nhập chiều cao (cm): "))

bmi = tinh_bmi(can_nang, cao)
print("Chỉ số BMI:", round(bmi,2))

#Bài 7.18 Miles ↔ mét
#Viết hàm chuyển đổi từ miles sang mét và ngược lại.
def miles_to_meters(miles):
    return miles * 1609.34

def meters_to_miles(meters):
    return meters / 1609.34

miles = float(input("Nhập số mile: "))
meters = miles_to_meters(miles)
print(f"{miles} mile = {meters} mét")

meters = float(input("Nhập số mét: "))
miles = meters_to_miles(meters)
print(f"{meters} mét = {miles} mile")

#Bài 7.19 Selection sort
#Viết hàm sắp xếp danh sách dùng Selection sort, hàm trả về danh sách đã được sắp xếp.
def selection_sort(arr):
    for i in range(len(arr)):
        min_idx = i
        for j in range(i+1,len(arr)):
            if arr[j] < arr[min_idx]:
                min_idx = j
        arr[i], arr[min_idx] = arr[min_idx], arr[i]
    return arr

danh_sach = input("Nhập danh sách số cách nhau bởi dấu cách: ").split()
danh_sach = [int(x) for x in danh_sach]
danh_sach_sap_xep = selection_sort(danh_sach)
print("Danh sách đã được sắp xếp:", danh_sach_sap_xep)

#Bài 7.20 Insertion sort
#Viết hàm sắp xếp danh sách dùng Insertion sort, hàm trả về danh sách đã được sắp xếp.
def insertion_sort(arr):
    for i in range(1,len(arr)):
        key = arr[i]
        j = i-1
        while j>=0 and arr[j] > key:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key
    return arr

danh_sach = input("Nhập danh sách số cách nhau bởi dấu cách: ").split()
danh_sach = [int(x) for x in danh_sach]
danh_sach_sap_xep = insertion_sort(danh_sach)
print("Danh sách đã được sắp xếp:", danh_sach_sap_xep)

#Bài 7B.21 Merge sort
#Viết hàm sắp xếp danh sách dùng Merge sort, hàm trả về danh sách đã được sắp xếp.
def merge_sort(arr):
    if len(arr)>1:
        mid = len(arr)//2
        L = arr[:mid]
        R = arr[mid:]
        merge_sort(L)
        merge_sort(R)
        i=j=k=0
        while i<len(L) and j<len(R):
            if L[i]<R[j]:
                arr[k]=L[i]; i+=1
            else:
                arr[k]=R[j]; j+=1
            k+=1
        while i<len(L):
            arr[k]=L[i]; i+=1; k+=1
        while j<len(R):
            arr[k]=R[j]; j+=1; k+=1
    return arr

danh_sach = input("Nhập danh sách số cách nhau bởi dấu cách: ").split()
danh_sach = [int(x) for x in danh_sach]
danh_sach_sap_xep = merge_sort(danh_sach)
print("Danh sách đã được sắp xếp:", danh_sach_sap_xep)

#Bài 7B.22 Buble sort
#Viết hàm sắp xếp danh sách dùng Buble sort, hàm trả về danh sách đã được sắp xếp.
def bubble_sort(arr):
    n = len(arr)
    for i in range(n-1):
        for j in range(n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

danh_sach = input("Nhập danh sách số cách nhau bởi dấu cách: ").split()
danh_sach = [int(x) for x in danh_sach]
danh_sach_sap_xep = bubble_sort(danh_sach)
print("Danh sách đã được sắp xếp:", danh_sach_sap_xep)

#Bài 7B.23 Số Armstrong
#Viết chương trình kiểm tra một số có phải là một số Armstrong hay không? Nếu đúng về True, ngược lại trả về False.
def la_armstrong(n):
    s = sum(int(d)**len(str(n)) for d in str(n))
    return s == n

n = int(input("Nhập số: "))
print("Có phải là số Armstrong ko?", la_armstrong(n))

#Bài 7B.25 Kiểm tra số CCCD
#Viết hàm kiểm tra một số CCCD có hợp lệ hay không biết rằng cấu trúc 12 chữ số trên số căn cước công dân có ý nghĩa như sau:
#•	03 chữ số đầu tiên là mã tỉnh, thành phố trực thuộc trung ương hoặc mã quốc gia nơi công dân đăng ký khai sinh,
#•	01 chữ số tiếp theo là mã giới tính của công dân
#•	02 chữ số tiếp theo là mã năm sinh của công dân;
#•	06 chữ số cuối là khoảng số ngẫu nhiên.
#Trong đó:
#•	Mã tỉnh, thành phố trực thuộc trung ương nơi công dân khai sinh có các mã từ 001 đến 0096 tương ứng với 63 tỉnh, thành phố trong cả nước. Công dân khai sinh ở Hà Nội có mã 001, Hải Phòng có mã 031, Đà Nẵng có mã 048, TP. Hồ Chí Minh có mã 079, Phú Yên có mã 054, Quãng Ngãi có mã 051, Bình Định có mã 052, Bà Rịa – Vũng Tàu có mã 077, Long An có mã 080,…
#•	Mã thế kỷ và mã giới tính được quy ước như sau:
#o	Thế kỷ 20 (từ năm 1900 đến hết năm 1999): Nam 0, nữ 1;
#o	Thế kỷ 21 (từ năm 2000 đến hết năm 2099): Nam 2, nữ 3;
#o	Thế kỷ 22 (từ năm 2100 đến hết năm 2199): Nam 4, nữ 5;
#o	Thế kỷ 23 (từ năm 2200 đến hết năm 2299): Nam 6, nữ 7;
#o	Thế kỷ 24 (từ năm 2300 đến hết năm 2399): Nam 8, nữ 9.
#	Mã năm sinh: Thể hiện hai số cuối năm sinh của công dân.
def kiem_tra_cccd(cccd: str) -> str:
    if len(cccd) != 12 or not cccd.isdigit():
        return "❌ CCCD phải gồm đúng 12 chữ số."

    ma_tinh = int(cccd[:3])
    if not (1 <= ma_tinh <= 96):
        return f"❌ Mã tỉnh {ma_tinh:03d} không hợp lệ (chỉ từ 001–096)."

    ma_gt = int(cccd[3])
    if not (0 <= ma_gt <= 9):
        return "❌ Mã giới tính không hợp lệ."

    nam_2so = int(cccd[4:6])

    if ma_gt in [0, 1]:   # 1900–1999
        nam_sinh = 1900 + nam_2so
    elif ma_gt in [2, 3]: # 2000–2099
        nam_sinh = 2000 + nam_2so
    elif ma_gt in [4, 5]: # 2100–2199
        nam_sinh = 2100 + nam_2so
    elif ma_gt in [6, 7]:
        nam_sinh = 2200 + nam_2so
    elif ma_gt in [8, 9]:
        nam_sinh = 2300 + nam_2so
    else:
        return "❌ Mã giới tính/ thế kỷ không hợp lệ."

    gioi_tinh = "Nam" if ma_gt % 2 == 0 else "Nữ"

    so_ngau_nhien = cccd[6:]
    if not so_ngau_nhien.isdigit():
        return "❌ 6 số cuối không hợp lệ."

    return f"✅ CCCD hợp lệ!\n- Mã tỉnh: {ma_tinh:03d}\n- Giới tính: {gioi_tinh}\n- Năm sinh: {nam_sinh}\n- Số cá nhân: {so_ngau_nhien}"

if __name__ == "__main__":
    cccd = input("Nhập số CCCD: ")
    print(kiem_tra_cccd(cccd))

#Bài 7B.26 Viết hàm tạo mã căn cước công dân
#Viết hàm tạo một số CCCD với thông tin cấu trúc mã như Bài 7B.25 Kiểm tra số CCCD
#với thông tin 6 số cuối được tạo ngẫu nhiên.
import random

def tao_cccd(ma_tinh, gioi_tinh, nam_sinh):
    ma_tinh = str(ma_tinh).zfill(3)

    the_ky = nam_sinh // 100
    ma_gt = {
        19: {'nam': 0, 'nu': 1},   # 1900–1999
        20: {'nam': 2, 'nu': 3},   # 2000–2099
        21: {'nam': 4, 'nu': 5},   # 2100–2199
        22: {'nam': 6, 'nu': 7},   # 2200–2299
        23: {'nam': 8, 'nu': 9},   # 2300–2399
    }

    if the_ky not in ma_gt:
        return "❌ Năm sinh ngoài phạm vi hỗ trợ (1900–2399)."

    if gioi_tinh not in ['nam', 'nu']:
        return "❌ Giới tính phải là 'nam' hoặc 'nu'."

    gt = ma_gt[the_ky][gioi_tinh]

    ma_ns = str(nam_sinh % 100).zfill(2)

    so_ngau_nhien = str(random.randint(0, 999999)).zfill(6)

    return ma_tinh + str(gt) + ma_ns + so_ngau_nhien

if __name__ == "__main__":
    ma_tinh = int(input("Nhập mã tỉnh (001–096): "))
    gioi_tinh = input("Nhập giới tính (nam/nu): ").lower()
    nam_sinh = int(input("Nhập năm sinh (yyyy): "))

    cccd = tao_cccd(ma_tinh, gioi_tinh, nam_sinh)
    print("➡️ Mã CCCD được tạo:", cccd)