# -*- coding: utf-8 -*-
"""Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Bài 5B.01 Kiểm tra số nguyên tố
#Kiểm tra một số n có phải là số nguyên tố hay không.
#Nếu đúng thì in True, nếu sai thì in False.
#Với n nhập từ bàn phím và đối số dòng lệnh.
n = int(input("Nhập số nguyên n = "))
so_ngto = True
if n<2:
  so_ngto = False
else:
  for i in range(2, int(n**0.5)+1):
    if n%i==0:
      so_ngto = False
      break
print(so_ngto)

#Bài 5B.02 Tính đa thức S(x, n)
#Viết chương trình cho phép nhập số nguyên dương x, n từ bàn phím và đối số dòng lệnh.
#Tính S(x, n) và hiển thị ra màn hình S(x, n).
#Với:
#𝑆(𝑥, 𝑛) = 𝑥^2 + 𝑥^4 + ⋯ + 𝑥^2𝑛
x=int(input("Nhập x = "))
n=int(input("Nhập n = "))

S=0
i=1
for i in range(i, n+1):
  S+=x**(2*i)
  print(f"Giá trị của S(x, n) = {S}")

#Bài 5B.03 Tính lãi suất
#Một khách hàng A, có số tiền là Y, đem gửi tiết kiệm với lãi suất mỗi năm là x %.
#Chu kỳ gửi là từng tháng, khi tới hạn thì tài khoản tiết kiệm sẽ tất toán và gửi tất cả <tiền lãi>,
#<tiền gốc> tiếp tục vào ngân hàng với lãi suất như cũ.
#Biết rằng nếu người dùng rút trước hạn thì sẽ tính lãi suất không kỳ hạn là 1% trên năm.
#Hãy viết chương trình cho người dùng biết được sau bao nhiêu tháng thì người dùng sẽ nhận được tối
#thiểu khoản tiền mong muốn. Người dùng sẽ nhập vào Y tiền gốc, Z tiền mong muốn đạt được, lãi suất x được nhập từ bàn phím và đối số dòng lệnh.
# Bài 5B.03 - Tính lãi suất tiết kiệm
# Chương trình này sẽ tính số tháng cần để số tiền tiết kiệm đạt mục tiêu.
# Bài 5B.03 - Tính lãi suất tiết kiệm

print("Chương trình tính số tháng cần để đạt tiền mong muốn.")
Y = float(input("Nhập số tiền gốc Y: "))
Z = float(input("Nhập số tiền mong muốn Z: "))
x = float(input("Nhập lãi suất x (%/năm): "))

lai_suat_thang = (x / 100) / 12
tien_hientai = Y
thang = 0

print("\n========================================================")
print("Tiến trình tăng tiền hàng tháng:")
print(f"Số tiền gốc ban đầu: {tien_hientai:,.0f} VND")

while tien_hientai < Z:
    thang = thang + 1
    tien_hientai = tien_hientai * (1 + lai_suat_thang)
    print(f"Tháng {thang}: {tien_hientai:,.0f} VND")
print("=========================================================")
print("\n Kết quả cuối cùng:")
print(f"Số tiền gốc ban đầu: {Y:,.0f} VND")
print(f"Số tiền mong muốn đạt được: {Z:,.0f} VND")
print(f"Lãi suất hàng năm: {x}%")
print("-" * 30)
print(f"Bạn cần gửi tiết kiệm trong tối thiểu {thang} tháng.")
print(f"Tổng số tiền cuối cùng sau {thang} tháng sẽ là: {tien_hientai:,.0f} VND")

#Bài 5B.04 In ra n dòng “Hello Python”
so_dong = int(input("Nhập số dòng: "))

if so_dong > 0:
    for i in range(so_dong):
        print("Hello Python")
else:
    print("Số dòng phải là một số nguyên dương.")

#Bài 5B.05 Tính tuổi người dùng
from datetime import date

nam_hien_tai = date.today().year

nam_sinh = int(input("Nhập năm sinh của bạn: "))

if nam_sinh < 1900 or nam_sinh > nam_hien_tai:
    print("Lỗi: Năm sinh không hợp lệ.")
else:
    tuoi = nam_hien_tai - nam_sinh
    print(f"Bạn {tuoi} tuổi.")

gio = int(input("Nhập giờ: "))
    phut = int(input("Nhập phút: "))
    giay = int(input("Nhập giây: "))
    k = int(input("Nhập số giây cần cộng thêm (k): "))

    tong_giay = gio * 3600 + phut * 60 + giay
    tong_giay_moi = tong_giay + k
    gio_moi = (tong_giay_moi // 3600) % 24
    phut_moi = (tong_giay_moi % 3600) // 60
    giay_moi = tong_giay_moi % 60
    print(f"Thời gian mới là: {str(gio_moi).zfill(2)}:{str(phut_moi).zfill(2)}:{str(giay_moi).zfill(2)}")

#Bài 5B.08 Số lượng chữ số và tổng các chữ số của số nguyên dương
n = int(input("Nhập một số nguyên dương n: "))
n_str = str(n)
so_luong_chu_so = len(n_str)

tong_chu_so = 0
for digit in n_str:
    tong_chu_so += int(digit)
print(f"Số lượng chữ số: {so_luong_chu_so}, tổng các chữ số: {tong_chu_so}")

#Bài 5B.09: Tính đa thức S(n)
n = int(input("Nhập một số nguyên dương n: "))
if n < 2:
    print(f"Giá trị của S(n) là: 0")
else:
    S = 0
    print("Các bước tính:")
    for i in range(1, n):
        term = i * (i + 1)
        print(f"Số thứ {i} là: {i} * {i+1} = {term}")
        S += term
        print(f"Tổng hiện tại: {S}")
    print(f"S(n) = {S}")

#Bài 5B.10 Tính đa thức S(x, n)
x = int(input("Nhập giá trị x: "))
n = int(input("Nhập số nguyên không âm n: "))
S = 0
print("Các bước tính:")
i = 0
while i <= n:
    so_thu = x**(2*i + 1)
    print(f"Số thứ {i}: {x} ^ {2*i} + {+ 1} = {so_thu}")
    S = S + so_thu
    print(f"Tổng S hiện tại: {S}")
    i = i + 1
print(f"S(x, n) = {S}")

#Bài 5B.11 Ước chung lớn nhất
a = int(input("Nhập số nguyên dương A: "))
b = int(input("Nhập số nguyên dương B: "))

print(f"Tìm ước chung lớn nhất của {a} và {b} bằng thuật toán Euclid")

while b != 0:
    so_du = a % b
    print(f"Thực hiện phép chia: {a} chia {b} được dư là {so_du}")
    a = b
    b = so_du
    print(f"Cập nhật a = {a} và b = {b}\n")

print(f"\n Ước chung lớn nhất là: {a}")

#Bài 5B.12 Chương trình chuyển đổi văn bản dùng vòng lặp
van_ban_co_dau = input("Nhập văn bản tiếng Việt có dấu: ")
van_ban_khong_dau = ""

for ky_tu in van_ban_co_dau:
    if ky_tu == 'á' or ky_tu == 'à' or ky_tu == 'ả' or ky_tu == 'ã' or ky_tu == 'ạ' or \
       ky_tu == 'ă' or ky_tu == 'ằ' or ky_tu == 'ắ' or ky_tu == 'ẳ' or ky_tu == 'ẵ' or ky_tu == 'ặ' or \
       ky_tu == 'â' or ky_tu == 'ầ' or ky_tu == 'ấ' or ky_tu == 'ẩ' or ky_tu == 'ẫ' or ky_tu == 'ậ':
        van_ban_khong_dau += 'a'
    elif ky_tu == 'Á' or ky_tu == 'À' or ky_tu == 'Ả' or ky_tu == 'Ã' or ky_tu == 'Ạ' or \
         ky_tu == 'Ă' or ky_tu == 'Ằ' or ky_tu == 'Ắ' or ky_tu == 'Ẳ' or ky_tu == 'Ẵ' or ky_tu == 'Ặ' or \
         ky_tu == 'Â' or ky_tu == 'Ầ' or ky_tu == 'Ấ' or ky_tu == 'Ẩ' or ky_tu == 'Ẫ' or ky_tu == 'Ậ':
        van_ban_khong_dau += 'A'
    elif ky_tu == 'đ':
        van_ban_khong_dau += 'd'
    elif ky_tu == 'Đ':
        van_ban_khong_dau += 'D'
    elif ky_tu == 'é' or ky_tu == 'è' or ky_tu == 'ẻ' or ky_tu == 'ẽ' or ky_tu == 'ẹ' or \
         ky_tu == 'ê' or ky_tu == 'ề' or ky_tu == 'ế' or ky_tu == 'ể' or ky_tu == 'ễ' or ky_tu == 'ệ':
        van_ban_khong_dau += 'e'
    elif ky_tu == 'É' or ky_tu == 'È' or ky_tu == 'Ẻ' or ky_tu == 'Ẽ' or ky_tu == 'Ẹ' or \
         ky_tu == 'Ê' or ky_tu == 'Ề' or ky_tu == 'Ế' or ky_tu == 'Ể' or ky_tu == 'Ễ' or ky_tu == 'Ệ':
        van_ban_khong_dau += 'E'
    elif ky_tu == 'í' or ky_tu == 'ì' or ky_tu == 'ỉ' or ky_tu == 'ĩ' or ky_tu == 'ị':
        van_ban_khong_dau += 'i'
    elif ky_tu == 'Í' or ky_tu == 'Ì' or ky_tu == 'Ỉ' or ky_tu == 'Ĩ' or ky_tu == 'Ị':
        van_ban_khong_dau += 'I'
    elif ky_tu == 'ó' or ky_tu == 'ò' or ky_tu == 'ỏ' or ky_tu == 'õ' or ky_tu == 'ọ' or \
         ky_tu == 'ô' or ky_tu == 'ồ' or ky_tu == 'ố' or ky_tu == 'ổ' or ky_tu == 'ỗ' or ky_tu == 'ộ' or \
         ky_tu == 'ơ' or ky_tu == 'ờ' or ky_tu == 'ớ' or ky_tu == 'ở' or ky_tu == 'ỡ' or ky_tu == 'ợ':
        van_ban_khong_dau += 'o'
    elif ky_tu == 'Ó' or ky_tu == 'Ò' or ky_tu == 'Ỏ' or ky_tu == 'Õ' or ky_tu == 'Ọ' or \
         ky_tu == 'Ô' or ky_tu == 'Ồ' or ky_tu == 'Ố' or ky_tu == 'Ổ' or ky_tu == 'Ỗ' or ky_tu == 'Ộ' or \
         ky_tu == 'Ơ' or ky_tu == 'Ờ' or ky_tu == 'Ớ' or ky_tu == 'Ở' or ky_tu == 'Ỡ' or ky_tu == 'Ợ':
        van_ban_khong_dau += 'O'
    elif ky_tu == 'ú' or ky_tu == 'ù' or ky_tu == 'ủ' or ky_tu == 'ũ' or ky_tu == 'ụ' or \
         ky_tu == 'ư' or ky_tu == 'ừ' or ky_tu == 'ứ' or ky_tu == 'ử' or ky_tu == 'ữ' or ky_tu == 'ự':
        van_ban_khong_dau += 'u'
    elif ky_tu == 'Ú' or ky_tu == 'Ù' or ky_tu == 'Ủ' or ky_tu == 'Ũ' or ky_tu == 'Ụ' or \
         ky_tu == 'Ư' or ky_tu == 'Ừ' or ky_tu == 'Ứ' or ky_tu == 'Ử' or ky_tu == 'Ữ' or ky_tu == 'Ự':
        van_ban_khong_dau += 'U'
    elif ky_tu == 'ý' or ky_tu == 'ỳ' or ky_tu == 'ỷ' or ky_tu == 'ỹ' or ky_tu == 'ỵ':
        van_ban_khong_dau += 'y'
    elif ky_tu == 'Ý' or ky_tu == 'Ỳ' or ky_tu == 'Ỷ' or ky_tu == 'Ỹ' or ky_tu == 'Ỵ':
        van_ban_khong_dau += 'Y'
    else:
        van_ban_khong_dau += ky_tu

print("Văn bản sau khi chuyển đổi là:", van_ban_khong_dau)

#Bài 5B.13 n số nguyên tố đầu tiên
n = int(input("Nhập n số nguyên tố đầu tiên cần tìm: "))

dem_so_nguyen_to = 0
so_hien_tai = 2

print(f"{n} số nguyên tố đầu tiên:")

while dem_so_nguyen_to < n:
    la_so_nguyen_to = True

    if so_hien_tai < 2:
        la_so_nguyen_to = False
    else:
        chia_het_cho = 2
        while chia_het_cho * chia_het_cho <= so_hien_tai:
            if so_hien_tai % chia_het_cho == 0:
                la_so_nguyen_to = False
                break
            chia_het_cho += 1

    if la_so_nguyen_to:
        print(f"Tìm thấy số nguyên tố thứ {dem_so_nguyen_to + 1}: {so_hien_tai}")
        dem_so_nguyen_to += 1

    so_hien_tai += 1

#Bài 6B.01 Tìm số lớn nhất trong 1 dãy số thực
day_so_da_nhap = []
so_lon_nhat_tim_thay = 0.0
lan_dau_tien_nhap = True

print("Nhập các số thực vào dãy. Nhấn Enter (để trống) để kết thúc.")

while True:
    dau_vao = input("Nhập số: ")

    if dau_vao == "":
        print("Kết thúc quá trình nhập.")
        break

    so_hien_tai = float(dau_vao)
    day_so_da_nhap.append(so_hien_tai)

    if lan_dau_tien_nhap:
        so_lon_nhat_tim_thay = so_hien_tai
        print(f"Số đầu tiên được nhập là {so_hien_tai}. Đặt {so_hien_tai} là số lớn nhất ban đầu.")
        lan_dau_tien_nhap = False
    else:
        if so_hien_tai > so_lon_nhat_tim_thay:
            so_lon_nhat_hien_tai = so_lon_nhat_tim_thay
            so_lon_nhat_tim_thay = so_hien_tai
            print(f"Tìm thấy số {so_hien_tai} lớn hơn số lớn nhất hiện tại là {so_lon_nhat_hien_tai}.")
            print(f"Cập nhật số lớn nhất thành {so_lon_nhat_tim_thay}.")
        else:
            print(f"Số {so_hien_tai} không lớn hơn số lớn nhất hiện tại là {so_lon_nhat_tim_thay}. Không có gì thay đổi.")

print("---")

if len(day_so_da_nhap) == 0:
    print("Không có số nào được nhập vào.")
else:
    print("Dãy số đã nhập:", day_so_da_nhap)
    print("Số lớn nhất trong dãy là:", so_lon_nhat_tim_thay)

#Bài 6B.02 Chương trình tính đa thức
gia_tri_x = float(input("Nhập giá trị x: "))
gia_tri_da_thuc = 0.0
bac_da_thuc = 0

print("Nhập các hệ số của đa thức. Nhập -1 để kết thúc.")

while True:
    dau_vao = input(f"Nhập hệ số của x^{bac_da_thuc} (hoặc -1 để kết thúc): ")

    if dau_vao == "-1":
        print("Kết thúc quá trình nhập hệ số.")
        break

    he_so = float(dau_vao)

    so_hang = he_so * (gia_tri_x**bac_da_thuc)
    gia_tri_da_thuc = gia_tri_da_thuc + so_hang

    print(f"Tính số hạng thứ {bac_da_thuc}: {he_so} * {gia_tri_x}^{bac_da_thuc} = {so_hang}")
    print(f"Tổng hiện tại của đa thức: {gia_tri_da_thuc}")

    bac_da_thuc = bac_da_thuc + 1

print("---")
print(f"Giá trị cuối cùng của đa thức tại x = {gia_tri_x} là: {gia_tri_da_thuc}")

#Bài 6B.03: Chương trình quản lý thương hiệu trà sữa
so_cua_hang = int(input("Nhập số lượng cửa hàng X: "))

danh_sach_doanh_so = []
tong_doanh_so = 0.0

for i in range(so_cua_hang):
    ten_cua_hang = input(f"Nhập tên cửa hàng thứ {i + 1}: ")
    doanh_so = float(input(f"Nhập doanh số của cửa hàng {ten_cua_hang}: "))
    danh_sach_doanh_so.append({"ten": ten_cua_hang, "doanh_so": doanh_so})
    tong_doanh_so += doanh_so

# Sắp xếp doanh số từ lớn tới bé
for i in range(len(danh_sach_doanh_so)):
    for j in range(i + 1, len(danh_sach_doanh_so)):
        if danh_sach_doanh_so[i]["doanh_so"] < danh_sach_doanh_so[j]["doanh_so"]:
            temp = danh_sach_doanh_so[i]
            danh_sach_doanh_so[i] = danh_sach_doanh_so[j]
            danh_sach_doanh_so[j] = temp

print("\n--- Doanh số bán hàng (sắp xếp từ lớn tới bé) ---")
for cua_hang in danh_sach_doanh_so:
    print(f"{cua_hang['ten']}: {cua_hang['doanh_so']}")

# Tính doanh số bán hàng trung bình
if so_cua_hang > 0:
    doanh_so_trung_binh = tong_doanh_so / so_cua_hang
    print(f"\nDoanh số bán hàng trung bình của {so_cua_hang} cửa hàng là: {doanh_so_trung_binh}")
else:
    print("\nKhông có cửa hàng nào được nhập.")

# Hiển thị cửa hàng có doanh số lớn nhất
if len(danh_sach_doanh_so) > 0:
    cua_hang_lon_nhat = danh_sach_doanh_so[0]
    print(f"\nCửa hàng có doanh số lớn nhất là: {cua_hang_lon_nhat['ten']} với doanh số {cua_hang_lon_nhat['doanh_so']}")

#Bài 6B.04: Chương trình quản lý danh sách
n = int(input("Nhập số nguyên n (số lượng phần tử): "))

L = []
for i in range(n):
    gia_tri = float(input(f"Nhập phần tử thứ {i + 1}: "))
    L.append(gia_tri)

print("\n--- Hiển thị các phần tử trong danh sách L ---")
print(L)

# Tìm min, max, và tổng
so_nho_nhat = L[0]
so_lon_nhat = L[0]
tong_cac_phan_tu = 0
so_duong = 0
so_am = 0

for gia_tri in L:
    if gia_tri < so_nho_nhat:
        so_nho_nhat = gia_tri
    if gia_tri > so_lon_nhat:
        so_lon_nhat = gia_tri

    tong_cac_phan_tu += gia_tri

    if gia_tri > 0:
        so_duong += 1
    elif gia_tri < 0:
        so_am += 1

print(f"\nGiá trị nhỏ nhất: {so_nho_nhat}")
print(f"Giá trị lớn nhất: {so_lon_nhat}")
print(f"Tổng các phần tử: {tong_cac_phan_tu}")
print(f"Số lượng số dương: {so_duong}")
print(f"Số lượng số âm: {so_am}")

# Sắp xếp
L_tang_dan = sorted(L)
L_giam_dan = sorted(L, reverse=True)

print(f"\nDanh sách đã sắp xếp tăng dần: {L_tang_dan}")
print(f"Danh sách đã sắp xếp giảm dần: {L_giam_dan}")

#Bài 6B.05: Chương trình quản lý danh sách sinh viên
so_sinh_vien = int(input("Nhập số lượng sinh viên: "))

danh_sach_sinh_vien = []

for i in range(so_sinh_vien):
    print(f"\nNhập thông tin sinh viên thứ {i + 1}:")
    sinh_vien = {}
    sinh_vien['ma_so_sv'] = input("Mã số sinh viên: ")
    sinh_vien['ho_ten'] = input("Họ và tên sinh viên: ")
    sinh_vien['lop'] = input("Lớp: ")
    sinh_vien['ngay_sinh'] = input("Ngày sinh: ")
    sinh_vien['gioi_tinh'] = input("Giới tính: ")
    danh_sach_sinh_vien.append(sinh_vien)

print("\n--- Hiển thị danh sách sinh viên ---")
for sv in danh_sach_sinh_vien:
    print(f"Mã số: {sv['ma_so_sv']}, Họ tên: {sv['ho_ten']}, Lớp: {sv['lop']}, Ngày sinh: {sv['ngay_sinh']}, Giới tính: {sv['gioi_tinh']}")

ma_so_can_tim = input("\nNhập mã số sinh viên cần tìm: ")
tim_thay = False

for sv in danh_sach_sinh_vien:
    if sv['ma_so_sv'] == ma_so_can_tim:
        print("\n--- Thông tin sinh viên cần tìm ---")
        print(f"Mã số: {sv['ma_so_sv']}")
        print(f"Họ và tên: {sv['ho_ten']}")
        print(f"Lớp: {sv['lop']}")
        print(f"Ngày sinh: {sv['ngay_sinh']}")
        print(f"Giới tính: {sv['gioi_tinh']}")
        tim_thay = True
        break

if not tim_thay:
    print("Không tìm thấy sinh viên với mã số đã nhập.")4

#Bài 6B.06: Chương trình quản lý cửa hàng tiện lợi
so_mat_hang = int(input("Nhập số lượng mặt hàng: "))

danh_sach_hang = []

for i in range(so_mat_hang):
    print(f"\nNhập thông tin mặt hàng thứ {i + 1}:")
    hang = {}
    hang['ten'] = input("Tên hàng: ")
    hang['so_luong'] = int(input("Số lượng: "))
    hang['gia_ban'] = float(input("Giá bán: "))
    hang['ngay_san_xuat'] = input("Ngày sản xuất: ")
    hang['ngay_het_han'] = input("Ngày hết hạn: ")
    hang['lo_san_xuat'] = input("Lô sản xuất: ")
    danh_sach_hang.append(hang)

# Tính tổng số lượng hàng hóa
tong_so_luong = 0
for hang in danh_sach_hang:
    tong_so_luong += hang['so_luong']

print(f"\nTổng số lượng hàng hóa trong cửa hàng là: {tong_so_luong}")

# Hiển thị mặt hàng có số lượng nhỏ hơn 10
print("\n--- Các mặt hàng có số lượng < 10 ---")
for hang in danh_sach_hang:
    if hang['so_luong'] < 10:
        print(f"Tên: {hang['ten']}, Số lượng: {hang['so_luong']}")

# Hiển thị mặt hàng có số lượng lớn hơn 50
print("\n--- Các mặt hàng có số lượng > 50 ---")
for hang in danh_sach_hang:
    if hang['so_luong'] > 50:
        print(f"Tên: {hang['ten']}, Số lượng: {hang['so_luong']}")

#Bài 6B.07: Chương trình quản lý kỳ thi tuyển sinh
so_thi_sinh = int(input("Nhập số lượng thí sinh: "))

danh_sach_thi_sinh = []

for i in range(so_thi_sinh):
    print(f"\nNhập thông tin thí sinh thứ {i + 1}:")
    thi_sinh = {}
    thi_sinh['so_bao_danh'] = input("Số báo danh (8 ký số): ")
    thi_sinh['ho_ten'] = input("Họ và tên thí sinh: ")
    thi_sinh['diem_toan'] = float(input("Điểm Toán (0-10): "))
    thi_sinh['diem_tieng_viet'] = float(input("Điểm Tiếng Việt (0-10): "))
    danh_sach_thi_sinh.append(thi_sinh)

print("\n--- Danh sách thí sinh ---")
for ts in danh_sach_thi_sinh:
    print(f"SBD: {ts['so_bao_danh']}, Họ tên: {ts['ho_ten']}, Toán: {ts['diem_toan']}, Tiếng Việt: {ts['diem_tieng_viet']}")

print("\n--- Danh sách thí sinh có tổng điểm >= 10 ---")
for ts in danh_sach_thi_sinh:
    tong_diem = ts['diem_toan'] + ts['diem_tieng_viet']
    if tong_diem >= 10:
        print(f"SBD: {ts['so_bao_danh']}, Họ tên: {ts['ho_ten']}, Tổng điểm: {tong_diem}")

print("\n--- Danh sách thí sinh có điểm liệt (điểm 0) ---")
for ts in danh_sach_thi_sinh:
    if ts['diem_toan'] == 0 or ts['diem_tieng_viet'] == 0:
        print(f"SBD: {ts['so_bao_danh']}, Họ tên: {ts['ho_ten']}")5

#Bài 6B.08: Chương trình quản lý cửa hàng Băng đĩa nhạc
so_bang_dia = int(input("Nhập số lượng băng đĩa: "))

danh_sach_bang_dia = []

for i in range(so_bang_dia):
    print(f"\nNhập thông tin băng đĩa thứ {i + 1}:")
    bang_dia = {}
    bang_dia['ten'] = input("Tên: ")
    bang_dia['the_loai'] = input("Thể loại: ")
    bang_dia['so_luong'] = int(input("Số lượng: "))
    bang_dia['gia_tien'] = float(input("Giá tiền: "))
    bang_dia['ngay_phat_hanh'] = input("Ngày phát hành: ")
    danh_sach_bang_dia.append(bang_dia)

print("\n--- Hiển thị thông tin băng đĩa ---")
print(f"{'Tên':<20}{'Thể loại':<15}{'Số lượng':<10}{'Giá tiền':<15}{'Ngày phát hành':<15}")
for bd in danh_sach_bang_dia:
    print(f"{bd['ten']:<20}{bd['the_loai']:<15}{bd['so_luong']:<10}{bd['gia_tien']:<15}{bd['ngay_phat_hanh']:<15}")

print("\n--- Các băng đĩa có giá rẻ nhất ---")
gia_re_nhat = -1

if len(danh_sach_bang_dia) > 0:
    gia_re_nhat = danh_sach_bang_dia[0]['gia_tien']
    for bd in danh_sach_bang_dia:
        if bd['gia_tien'] < gia_re_nhat:
            gia_re_nhat = bd['gia_tien']

    print(f"{'Tên':<20}{'Thể loại':<15}{'Giá tiền':<15}")
    for bd in danh_sach_bang_dia:
        if bd['gia_tien'] == gia_re_nhat:
            print(f"{bd['ten']:<20}{bd['the_loai']:<15}{bd['gia_tien']:<15}")
else:
    print("Không có băng đĩa nào được nhập.")