
# -*- coding: utf-8 -*-
"""Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#4B1
# Viết chương trình tìm số lớn nhất trong 3 số a, b và c.
# Với đầu vào là a, b, c được nhập từ bàn phím và đối số dòng lệnh.
import sys

def find_max(a, b, c):
    if a >= b and a >= c:
        return a
    elif b >= a and b >= c:
        return b
    else:
        return c

# Xử lý đầu vào từ bàn phím hoặc đối số dòng lệnh
if len(sys.argv) > 3:
    try:
        a = float(sys.argv[1])
        b = float(sys.argv[2])
        c = float(sys.argv[3])
    except ValueError:
        print("Lỗi: Đối số dòng lệnh phải là số.")
        sys.exit()
else:
    try:
        a = float(input("Nhập số a: "))
        b = float(input("Nhập số b: "))
        c = float(input("Nhập số c: "))
    except ValueError:
        print("Lỗi: Vui lòng nhập một số hợp lệ.")
        sys.exit()

max_number = find_max(a, b, c)
print(f"Số lớn nhất trong ba số là: {max_number}")

#4B2
# Giải và biện luận phương trình bậc nhất: ax + b = 0
try:
    a = float(input("Nhập a: "))
    b = float(input("Nhập b: "))

    if a == 0:
        if b == 0:
            print("Phương trình có vô số nghiệm.")
        else:
            print("Phương trình vô nghiệm.")
    else:
        x = -b / a
        print(f"Phương trình có nghiệm duy nhất: x = {x}")
except ValueError:
    print("Lỗi: Vui lòng nhập một số hợp lệ.")

#4B3
# Viết chương trình giải phương trình bậc hai ax^2 + bx + c = 0
# Với a, b, c được nhập từ bàn phím và đối số dòng lệnh.
import sys
import math

# Xử lý đầu vào từ bàn phím hoặc đối số dòng lệnh
if len(sys.argv) > 3:
    try:
        a = float(sys.argv[1])
        b = float(sys.argv[2])
        c = float(sys.argv[3])
    except ValueError:
        print("Lỗi: Đối số dòng lệnh phải là số.")
        sys.exit()
else:
    try:
        a = float(input("Nhập a: "))
        b = float(input("Nhập b: "))
        c = float(input("Nhập c: "))
    except ValueError:
        print("Lỗi: Vui lòng nhập một số hợp lệ.")
        sys.exit()

if a == 0:
    # Trở thành phương trình bậc nhất
    if b == 0:
        if c == 0:
            print("Phương trình có vô số nghiệm.")
        else:
            print("Phương trình vô nghiệm.")
    else:
        x = -c / b
        print(f"Phương trình bậc nhất có nghiệm duy nhất: x = {x}")
else:
    delta = b**2 - 4*a*c
    if delta < 0:
        print("Phương trình vô nghiệm.")
    elif delta == 0:
        x = -b / (2 * a)
        print(f"Phương trình có nghiệm kép: x1 = x2 = {x}")
    else:
        x1 = (-b - math.sqrt(delta)) / (2 * a)
        x2 = (-b + math.sqrt(delta)) / (2 * a)
        print(f"Phương trình có hai nghiệm phân biệt:")
        print(f"x1 = {x1}")
        print(f"x2 = {x2}")

#4B4
# Viết chương trình cho người dùng nhập vào từ bàn phím hai số a, b và một ký tự ch.
# Kiểm tra nếu ch là +, -, *, / thì thực hiện phép tính, ngược lại thông báo lỗi.
import sys

# Xử lý đầu vào từ bàn phím hoặc đối số dòng lệnh
if len(sys.argv) > 3:
    try:
        a = float(sys.argv[1])
        b = float(sys.argv[2])
        ch = sys.argv[3]
    except ValueError:
        print("Lỗi: Đối số a và b phải là số.")
        sys.exit()
else:
    try:
        a = float(input("Nhập số a: "))
        b = float(input("Nhập số b: "))
        ch = input("Nhập toán tử (+, -, *, /): ")
    except ValueError:
        print("Lỗi: Vui lòng nhập một số hợp lệ.")
        sys.exit()

if ch == '+':
    result = a + b
    print(f"{a} + {b} = {result}")
elif ch == '-':
    result = a - b
    print(f"{a} - {b} = {result}")
elif ch == '*':
    result = a * b
    print(f"{a} * {b} = {result}")
elif ch == '/':
    if b == 0:
        print("Lỗi: Không thể chia cho 0.")
    else:
        result = a / b
        print(f"{a} / {b} = {result}")
else:
    print("Ký tự ch không phải là một toán tử.")

#4B5
# Chương trình tính phụ cấp dựa trên chức vụ
ho_ten = input("Nhập họ tên cán bộ: ")
chuc_vu = input("Nhập chức vụ (Giám đốc, Phó Giám đốc, Trưởng phòng,...): ")

phu_cap = 0
# Dùng .lower() để so sánh không phân biệt chữ hoa, chữ thường
if chuc_vu.lower() == "giám đốc":
    phu_cap = 5000000
elif chuc_vu.lower() == "phó giám đốc":
    phu_cap = 3000000
elif chuc_vu.lower() == "trưởng phòng":
    phu_cap = 500000
else:
    phu_cap = 0

print(f"Cán bộ {ho_ten} với chức vụ {chuc_vu} có phụ cấp là: {phu_cap:,} đồng.")

#4B6
# Nhận vào mã sinh viên, họ tên và điểm rèn luyện để xét hạnh kiểm.
# Hạnh kiểm dựa trên điểm: Xuất sắc (>=90), Tốt (>=80), Khá (>=65), Trung bình (>=50), Yếu (<50).
import sys

if len(sys.argv) > 3:
    ma_sv = sys.argv[1]
    ho_ten = sys.argv[2]
    try:
        diem_ren_luyen = float(sys.argv[3])
    except ValueError:
        print("Lỗi: Điểm rèn luyện phải là một số.")
        sys.exit()
else:
    ma_sv = input("Nhập mã sinh viên: ")
    ho_ten = input("Nhập họ tên sinh viên: ")
    try:
        diem_ren_luyen = float(input("Nhập điểm rèn luyện: "))
    except ValueError:
        print("Lỗi: Vui lòng nhập một số hợp lệ.")
        sys.exit()

if diem_ren_luyen >= 90:
    hanh_kiem = "Xuất sắc"
elif diem_ren_luyen >= 80:
    hanh_kiem = "Tốt"
elif diem_ren_luyen >= 65:
    hanh_kiem = "Khá"
elif diem_ren_luyen >= 50:
    hanh_kiem = "Trung bình"
else:
    hanh_kiem = "Yếu"

print(f"Sinh viên {ho_ten} (Mã SV: {ma_sv}) có hạnh kiểm: {hanh_kiem}")

#4B7
# Chương trình tính tiền điện theo giá bậc thang
try:
    so_dien = float(input("Nhập số điện tiêu thụ (kWh): "))

    tien_dien = 0
    if so_dien > 400:
        tien_dien += (so_dien - 400) * 2927
        so_dien = 400
    if so_dien > 300:
        tien_dien += (so_dien - 300) * 2834
        so_dien = 300
    if so_dien > 200:
        tien_dien += (so_dien - 200) * 2536
        so_dien = 200
    if so_dien > 100:
        tien_dien += (so_dien - 100) * 2014
        so_dien = 100
    if so_dien > 50:
        tien_dien += (so_dien - 50) * 1734
        so_dien = 50
    if so_dien > 0:
        tien_dien += so_dien * 1678

    thue_gtgt = tien_dien * 0.1
    tong_cong = tien_dien + thue_gtgt

    print(f"\nTổng số kWh tiêu thụ: {so_dien:.0f}")
    print(f"Tiền điện chưa thuế: {tien_dien:,.0f} đồng")
    print(f"Thuế GTGT (10%): {thue_gtgt:,.0f} đồng")
    print(f"Tổng cộng tiền thanh toán: {tong_cong:,.0f} đồng")
except ValueError:
    print("Lỗi: Vui lòng nhập một số hợp lệ.")

#4B8
# Nhận độ dài ba cạnh của tam giác, kiểm tra xem chúng có tạo thành tam giác không.
# Nếu có, kiểm tra xem đó có phải là tam giác đều không.
import sys

if len(sys.argv) > 3:
    try:
        a = float(sys.argv[1])
        b = float(sys.argv[2])
        c = float(sys.argv[3])
    except ValueError:
        print("Lỗi: Các cạnh phải là số.")
        sys.exit()
else:
    try:
        a = float(input("Nhập cạnh a: "))
        b = float(input("Nhập cạnh b: "))
        c = float(input("Nhập cạnh c: "))
    except ValueError:
        print("Lỗi: Vui lòng nhập một số hợp lệ.")
        sys.exit()

if a + b > c and a + c > b and b + c > a:
    print("Ba cạnh trên thỏa mãn điều kiện hình tam giác.")
    if a == b and b == c:
        print("Tam giác trên là tam giác đều.")
    else:
        print("Tam giác trên không là tam giác đều.")
else:
    print("Ba cạnh trên không thỏa mãn điều kiện hình tam giác.")

#4B9
# Kiểm tra tam giác vuông
try:
    a = float(input("Nhập cạnh a: "))
    b = float(input("Nhập cạnh b: "))
    c = float(input("Nhập cạnh c: "))

    if a + b > c and a + c > b and b + c > a:
        print("Ba cạnh trên thỏa mãn điều kiện hình tam giác.")
        # Dùng round() để tránh sai số dấu phẩy động
        if round(a**2 + b**2, 2) == round(c**2, 2) or \
           round(a**2 + c**2, 2) == round(b**2, 2) or \
           round(b**2 + c**2, 2) == round(a**2, 2):
            print("Tam giác trên là tam giác vuông.")
        else:
            print("Tam giác trên không là tam giác vuông.")
    else:
        print("Ba cạnh trên không thỏa mãn điều kiện hình tam giác.")
except ValueError:
    print("Lỗi: Vui lòng nhập một số hợp lệ.")

#4B10
# Chuyển đổi số giữa các hệ nhị phân, thập phân, bát phân và thập lục phân.
# Với đầu vào là x (số cần chuyển), y (hệ cơ số của x), z (cơ số cần chuyển đổi).
import sys

def convert_base(number_str, from_base, to_base):
    try:
        # Chuyển đổi số từ cơ số ban đầu sang thập phân
        decimal_num = int(number_str, from_base)

        # Chuyển đổi từ thập phân sang cơ số cần chuyển đổi
        if to_base == 2:
            return bin(decimal_num)[2:]
        elif to_base == 8:
            return oct(decimal_num)[2:]
        elif to_base == 10:
            return str(decimal_num)
        elif to_base == 16:
            return hex(decimal_num)[2:].upper()
        else:
            return "Cơ số đích không hợp lệ (2, 8, 10, 16)."
    except ValueError:
        return "Lỗi: Số không hợp lệ với cơ số gốc."

# Xử lý đầu vào từ bàn phím hoặc đối số dòng lệnh
if len(sys.argv) > 3:
    x = sys.argv[1]
    try:
        y = int(sys.argv[2])
        z = int(sys.argv[3])
    except ValueError:
        print("Lỗi: Cơ số phải là số nguyên.")
        sys.exit()
else:
    x = input("Nhập số cần chuyển đổi: ")
    try:
        y = int(input("Nhập hệ cơ số của x (2, 8, 10, 16): "))
        z = int(input("Nhập cơ số cần chuyển đổi (2, 8, 10, 16): "))
    except ValueError:
        print("Lỗi: Vui lòng nhập một số hợp lệ.")
        sys.exit()

result = convert_base(x, y, z)
print(f"Số {x} (hệ {y}) sau khi chuyển sang hệ {z} là: {result}")

#4B11
# Chuyển đổi văn bản tiếng Việt có dấu thành không dấu
chu_viet_khong_dau = {
    'á': 'a', 'à': 'a', 'ả': 'a', 'ã': 'a', 'ạ': 'a', 'Á': 'A', 'À': 'A', 'Ả': 'A', 'Ã': 'A', 'Ạ': 'A',
    'ă': 'a', 'ằ': 'a', 'ắ': 'a', 'ẳ': 'a', 'ẵ': 'a', 'ặ': 'a', 'Ă': 'A', 'Ằ': 'A', 'Ắ': 'A', 'Ẳ': 'A', 'Ẵ': 'A', 'Ặ': 'A',
    'â': 'a', 'ầ': 'a', 'ấ': 'a', 'ẩ': 'a', 'ẫ': 'a', 'ậ': 'a', 'Â': 'A', 'Ầ': 'A', 'Ấ': 'A', 'Ẩ': 'A', 'Ẫ': 'A', 'Ậ': 'A',
    'đ': 'd', 'Đ': 'D',
    'é': 'e', 'è': 'e', 'ẻ': 'e', 'ẽ': 'e', 'ẹ': 'e', 'É': 'E', 'È': 'E', 'Ẻ': 'E', 'Ẽ': 'E', 'Ẹ': 'E',
    'ê': 'e', 'ề': 'e', 'ế': 'e', 'ể': 'e', 'ễ': 'e', 'ệ': 'e', 'Ê': 'E', 'Ề': 'E', 'Ể': 'E', 'Ễ': 'E', 'Ệ': 'E',
    'í': 'i', 'ì': 'i', 'ỉ': 'i', 'ĩ': 'i', 'ị': 'i', 'Í': 'I', 'Ì': 'I', 'Ỉ': 'I', 'Ĩ': 'I', 'Ị': 'I',
    'ó': 'o', 'ò': 'o', 'ỏ': 'o', 'õ': 'o', 'ọ': 'o', 'Ó': 'O', 'Ò': 'O', 'Ỏ': 'O', 'Õ': 'O', 'Ọ': 'O',
    'ô': 'o', 'ồ': 'o', 'ố': 'o', 'ổ': 'o', 'ỗ': 'o', 'ộ': 'o', 'Ô': 'O', 'Ồ': 'O', 'Ố': 'O', 'Ổ': 'O', 'Ỗ': 'O', 'Ộ': 'O',
    'ơ': 'o', 'ờ': 'o', 'ớ': 'o', 'ở': 'o', 'ỡ': 'o', 'ợ': 'o', 'Ơ': 'O', 'Ờ': 'O', 'Ớ': 'O', 'Ở': 'O', 'Ỡ': 'O', 'Ợ': 'O',
    'ú': 'u', 'ù': 'u', 'ủ': 'u', 'ũ': 'u', 'ụ': 'u', 'Ú': 'U', 'Ù': 'U', 'Ủ': 'U', 'Ũ': 'U', 'Ụ': 'U',
    'ư': 'u', 'ừ': 'u', 'ứ': 'u', 'ử': 'u', 'ữ': 'u', 'ự': 'u', 'Ư': 'U', 'Ừ': 'U', 'Ứ': 'U', 'Ử': 'U', 'Ữ': 'U', 'Ự': 'U',
    'ý': 'y', 'ỳ': 'y', 'ỷ': 'y', 'ỹ': 'y', 'ỵ': 'y', 'Ý': 'Y', 'Ỳ': 'Y', 'Ỷ': 'Y', 'Ỹ': 'Y', 'Ỵ': 'Y'
}

def chuyen_doi(text):
    result = ""
    for char in text:
        result += chu_viet_khong_dau.get(char, char)
    return result

s = input("Nhập văn bản tiếng Việt có dấu: ")
s_khong_dau = chuyen_doi(s)
print("Văn bản không dấu là:", s_khong_dau)

#4B12
# Kiểm tra một số có phải là số Armstrong hay không
try:
    number = int(input("Nhập một số nguyên: "))

    if number < 0:
        is_armstrong = False
    else:
        num_str = str(number)
        num_digits = len(num_str)

        total = 0
        for digit in num_str:
            total += int(digit) ** num_digits

        is_armstrong = (total == number)

    print(is_armstrong)
except ValueError:
    print("Lỗi: Vui lòng nhập một số hợp lệ.")

#4B13
# Kiểm tra một số có phải là số hoàn hảo hay không
try:
    number = int(input("Nhập một số nguyên: "))

    if number <= 0:
        is_perfect = False
    else:
        sum_of_divisors = 0
        for i in range(1, int(number**0.5) + 1):
            if number % i == 0:
                sum_of_divisors += i
                if i * i != number and i != 1:
                    sum_of_divisors += number // i

        is_perfect = (sum_of_divisors == number)

    print(is_perfect)
except ValueError:
    print("Lỗi: Vui lòng nhập một số hợp lệ.")

#4B14
# Kiểm tra một chuỗi có phải là email hợp lệ không
email = input("Nhập địa chỉ email: ")

# Kiểm tra có đúng 1 ký tự '@'
if email.count('@') != 1:
    print("Địa chỉ email không hợp lệ.")
else:
    parts = email.split('@')
    x = parts[0]
    y_z = parts[1]

    # Kiểm tra phần x không rỗng
    if not x:
        print("Địa chỉ email không hợp lệ.")
    # Kiểm tra phần y.z có chứa '.' và không rỗng
    elif '.' not in y_z or not y_z:
        print("Địa chỉ email không hợp lệ.")
    else:
        domain_parts = y_z.split('.')
        y = domain_parts[0]
        z = domain_parts[1]

        # Kiểm tra y và z không rỗng
        if not y or not z:
            print("Địa chỉ email không hợp lệ.")
        else:
            print("Địa chỉ email hợp lệ.")

#4B15
# Kiểm tra số CCCD có hợp lệ không
scccd = input("Nhập số CCCD: ")

# Kiểm tra độ dài
if len(scccd) != 12:
    print("Chuỗi không hợp lệ.")
# Kiểm tra tất cả ký tự là chữ số
elif not scccd.isdigit():
    print("Chuỗi không hợp lệ.")
else:
    print("Chuỗi hợp lệ.")

#4B16
# Kiểm tra ký tự c có xuất hiện trong chuỗi s không
s = input("Nhập chuỗi s: ")
c = input("Nhập ký tự c: ")

# Sử dụng phương thức count() để đếm số lần xuất hiện
count = s.count(c)

if count > 0:
    print(f"Ký tự '{c}' xuất hiện {count} lần trong chuỗi '{s}'.")
else:
    print(f"Không tìm thấy ký tự '{c}' trong chuỗi.")

#4B17
# Kiểm tra chuỗi s2 có trong chuỗi s1 không
s1 = input("Nhập chuỗi s1: ")
s2 = input("Nhập chuỗi s2: ")

# Sử dụng phương thức find() để tìm vị trí
position = s1.find(s2)

if position != -1:
    print(f"Chuỗi '{s2}' xuất hiện trong chuỗi '{s1}' tại vị trí đầu tiên: {position}")
else:
    print(f"Không tìm thấy chuỗi '{s2}' trong chuỗi '{s1}'.")